version: '2.0'

networks:
  funhouse:
    driver: bridge

services:
  flexo:
    build: .
    command: npm start
    env_file: .env
    ports:
      - '7715:3000'
    restart: on-failure
    networks:
      - funhouse
